version: 1.0
workflows:
   - subclass: WDL
     primaryDescriptorPath: /inst/workflow/Rcollectlworkflow_hca_loom.wdl
     testParameterFiles:
         - /inst/workflow/Rcollectlworkflow_hca_loom_inputs.json
